### PR TITLE
Transient error happening in container existence check will lead to container not found exception

### LINKED ISSUE #258: Transient error leads to container not found exception
**Describe the bug**
We find that a transient error (e.g., temporary 503 server is busy) in `CreateIfNotExistsAsync`/`ExistsAsync` can lead to an unhandled container not found exception.
More concretely, in `BeforeMessageSend` 
```
try
{
  // Will only work for Shared Key or Account SAS. For Container SAS will throw an exception.
  if (! await container.ExistsAsync().ConfigureAwait(false))
  {
    await container.CreateIfNotExistsAsync().ConfigureAwait(false);
  }
}
catch (StorageException)
{
  // swallow in case a container SAS is used
}
...
await blob.UploadFromByteArrayAsync(message.Body, 0, message.Body.Length).ConfigureAwait(false);
```
If `CreateIfNotExistsAsync` or `ExistsAsync` fails due to some transient error (like when the server is busy), the exception will be swallowed in the catch block without being checked. As a result, the container is not successfully created. The following upload operation will fail due to the container not found exception.

**To Reproduce**
As shown above, when the `CreateIfNotExistsAsync` in `BeforeMessageSend` fails due to a transient error, container not found exception will happen in the following blob operations.

**Expected behavior**
The exception should be checked in the catch block to decide whether to swallow/retry/rethrow depending on the exception type. For example, if it is caused by some transient error, it can either retry or just rethrow the exception.

**Additional context**
We are willing to send a PR to help on this issue, if retry/rethrow the transient error exception is considered as a better practice than swallow.

### PR DESCRIPTION
**Pull request by rmt-2021**
### Bug description
We found that transient network errors (e.g., 503 server busy or timeout) may fail the [ExistsAsync](https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/blob/a3739a16ceb0a4a10a23b7f82c3ff868a0ee019d/src/ServiceBus.AttachmentPlugin/AzureStorageAttachment.cs#L49) SDK API. More precisely, if the `container.ExistsAsync()` fails due to transient error(like service unavailable), the exception will be swallowed by the `catch` block. Therefore, the following [line of code](https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/blob/a3739a16ceb0a4a10a23b7f82c3ff868a0ee019d/src/ServiceBus.AttachmentPlugin/AzureStorageAttachment.cs#L66) will fail due to container not found exception.
```
try
{
    // Will only work for Shared Key or Account SAS. For Container SAS will throw an exception.
    if (! await container.ExistsAsync().ConfigureAwait(false))
    {
        await container.CreateIfNotExistsAsync().ConfigureAwait(false);
    }
}
catch (StorageException)
{
    // swallow in case a container SAS is used
}
...
await blob.UploadFromByteArrayAsync(message.Body, 0, message.Body.Length).ConfigureAwait(false);
```
and the output error message is `Microsoft.Azure.Storage.StorageException : The specified container does not exist`.

### How to reproduce
Transient errors like 503 service unavailable are likely to happen when creating container, consequently the method `container.ExistsAsync()` will fail. Hence, [this line](https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/blob/a3739a16ceb0a4a10a23b7f82c3ff868a0ee019d/src/ServiceBus.AttachmentPlugin/AzureStorageAttachment.cs#L66) will fail due to container not found exception.
### Expected behaviour
The exception should be checked in the catch block to decide whether to swallow/retry/rethrow depending on the exception type. For example, if it is caused by some transient error, it can either retry or just rethrow the exception.
### **Additional context**
This bug is similar to the #258 we found. We are willing to send a PR to help on this issue, if retry/rethrow the transient error exception is considered as a better practice than swallow.

### CODE REVIEW

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBus.AttachmentPlugin 0.0.1039-preview completed](https://ci.appveyor.com/project/seanfeldman/servicebus-attachmentplugin/builds/44378629) (commit https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/commit/a380c9d580 by @rmt-2021)

File: src/ServiceBus.AttachmentPlugin/AzureStorageAttachment.cs [hunk 1]
```diff
@@ -46,14 +46,16 @@ public override async Task<Message> BeforeMessageSend(Message message)
...
                 {
                     await container.CreateIfNotExistsAsync().ConfigureAwait(false);
                 }
             }
-            catch (StorageException)
+            catch (StorageException exception)
             {
                 // swallow in case a container SAS is used
+                if (exception.RequestInformation.HttpStatusCode != (int)System.Net.HttpStatusCode.Forbidden)
+                    throw exception;
```
Comment (SeanFeldman) [inline src/ServiceBus.AttachmentPlugin/AzureStorageAttachment.cs]: @rmt-2021, if I understand the change correctly, the caught exception should be rethrown here, but it should be rethrown, not throw a new exception by re-using the captured exception object. If I got it right, I suggest changing the rethrow code to follow the .NET standard exception rethrowing practice.

```suggestion
                if (exception.RequestInformation.HttpStatusCode != (int)System.Net.HttpStatusCode.Forbidden)
                {
                    throw;
                }
```

Comment (SeanFeldman) [reply src/ServiceBus.AttachmentPlugin/AzureStorageAttachment.cs]: If you agree, you can `Commit suggestion,` and I'll merge the PR.

**Review by SeanFeldman — CHANGES_REQUESTED** [review]

**Comment by rmt-2021** [comment]
Thanks for your suggestion! I have made the`Commit suggestion`.

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBus.AttachmentPlugin 0.0.1040-preview completed](https://ci.appveyor.com/project/seanfeldman/servicebus-attachmentplugin/builds/44394507) (commit https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/commit/195d850d5b by @rmt-2021)

**Review by SeanFeldman — APPROVED** [review]

**Comment by SeanFeldman** [comment]
@rmt-2021 Thank you for raising this PR.

Please note that the plugin is deprecated as the Service Bus it was developed for is also deprecated. I'm keeping the repo around for legacy projects but no longer publishing to NuGet.
